In [1]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import json
import numpy as np
from pathlib import Path

In [6]:
tmp_str = '/nfs/turbo/coe-vvh/ljr/Censorship/data/v_0305/dataset_test_uniq.csv'
df = pd.read_csv(tmp_str, engine='python', index_col=0)
df['withheld'].value_counts().values

array([13759,  1483,  1044,   892,   500,   211,   187,   149,    47,
          24,    20,     9,     3,     1,     1,     1,     1,     1,
           1,     1,     1,     1,     1])

In [7]:
censored = []
for _, row in df.iterrows():
    if type(row['withheld']) == float:
        censored.append(0)
    else:
        censored.append(1)
df['censored'] = censored
df.to_csv(tmp_str)

# select en text

In [12]:
tmp_str = '/nfs/turbo/coe-vvh/ljr/Censorship/data/v_0305/dataset_train_p.csv'
df = pd.read_csv(tmp_str, engine='python', index_col=0)
df_new = df.loc[df['lang'] == 'en']
df_new.to_csv(tmp_str[:-4] + '_en.csv')

:

# others

In [5]:
def sep_df(df):
    df_tr = df.loc[df['lang'] == 'tr']
    df_others = df.loc[df['lang'] != 'tr']
    return df_tr, df_others


df_train = pd.read_csv('/cluster/project/sachan/jiarliu/censorship/data/dataset_train.csv', index_col=0)
df_val = pd.read_csv('/cluster/project/sachan/jiarliu/censorship/data/dataset_val.csv', index_col=0)
df_test = pd.read_csv('/cluster/project/sachan/jiarliu/censorship/data/dataset_test.csv', index_col=0)

df_train_tr, df_train_others = sep_df(df_train)
df_val_tr, df_val_others = sep_df(df_val)
df_test_tr, df_test_others = sep_df(df_test)

df_train_tr.to_csv('/cluster/project/sachan/jiarliu/censorship/data/turkish/train.csv')
df_val_tr.to_csv('/cluster/project/sachan/jiarliu/censorship/data/turkish/val.csv')
df_test_tr.to_csv('/cluster/project/sachan/jiarliu/censorship/data/turkish/test.csv')
df_train_others.to_csv('/cluster/project/sachan/jiarliu/censorship/data/others/train.csv')
df_val_others.to_csv('/cluster/project/sachan/jiarliu/censorship/data/others/val.csv')
df_test_others.to_csv('/cluster/project/sachan/jiarliu/censorship/data/others/test.csv')

/tmp/ipykernel_8028/1081554479.py:7: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df_train = pd.read_csv('/cluster/project/sachan/jiarliu/censorship/data/dataset_train.csv', index_col=0)

In [2]:
df = pd.read_csv('/cluster/project/sachan/jiarliu/censorship/data/dataset_full.csv')

/tmp/ipykernel_8028/2173332577.py:1: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/cluster/project/sachan/jiarliu/censorship/data/dataset_full.csv')

In [9]:
df.drop(columns=['Unnamed: 0.1', 'Unnamed: 0'], inplace=True)

In [4]:
df['lang'].value_counts()

en                                                                             291262
tr                                                                             153771
es                                                                              24935
zxx                                                                             15536
ar                                                                              12373
                                                                                ...
{'retweet_count': 22, 'reply_count': 1, 'like_count': 3, 'quote_count': 0}          1
{'retweet_count': 12, 'reply_count': 3, 'like_count': 5, 'quote_count': 0}          1
am                                                                                  1
{'retweet_count': 9, 'reply_count': 0, 'like_count': 0, 'quote_count': 0}           1
{'retweet_count': 51, 'reply_count': 8, 'like_count': 10, 'quote_count': 0}         1
Name: lang, Length: 113, dtype: int64

In [7]:
def eval_wrapper(row):
    # print(row)
    if type(row) == float and np.isnan(row):
        return row
    row = eval(row)
    return row
tmp = df['public_metrics'].apply(lambda row: eval_wrapper(row))

In [10]:
df['retweet_count'] = tmp.apply(lambda row: row['retweet_count'] if type(row) == dict and 'retweet_count' in row else None)
df['reply_count'] = tmp.apply(lambda row: row['reply_count'] if type(row) == dict and 'retweet_count' in row else None)
df['like_count'] = tmp.apply(lambda row: row['like_count'] if type(row) == dict and 'retweet_count' in row else None)
df['quote_count'] = tmp.apply(lambda row: row['quote_count'] if type(row) == dict and 'retweet_count' in row else None)
df

,Unnamed: 0,public_metrics,edit_history_tweet_ids,entities,lang,created_at,possibly_sensitive,id,text,author_id,withheld,geo,censored,retweet_count,reply_count,like_count,quote_count
0,0,"{'retweet_count': 35, 'reply_count': 9, 'like_...",['258919048455270401'],"{'hashtags': [{'start': 100, 'end': 108, 'tag'...",en,2012-10-18T13:14:46.000Z,False,258919048455270400.0,Look at this regime: They gossip viciously abo...,3.423007e+08,NaN,NaN,1,35.0,9.0,11.0,0.0
1,1,"{'retweet_count': 1, 'reply_count': 0, 'like_c...",['310221306102706176'],"{'mentions': [{'start': 3, 'end': 12, 'usernam...",pt,2013-03-09T02:51:37.000Z,False,310221306102706176.0,RT @verdazzo: Adeus @HOTWords_BR.,1.010271e+09,"{'copyright': False, 'country_codes': ['BR']}",NaN,1,1.0,0.0,0.0,0.0
2,2,"{'retweet_count': 193, 'reply_count': 24, 'lik...",['263737069891878912'],NaN,ru,2012-10-31T20:19:52.000Z,False,263737069891878880.0,"Друзья, совершайте суицид, это весело. Я пробо...",1.882079e+07,"{'copyright': False, 'country_codes': ['RU']}",NaN,1,193.0,24.0,45.0,2.0
3,3,"{'retweet_count': 45, 'reply_count': 27, 'like...",['367377468870500353'],"{'urls': [{'start': 98, 'end': 108, 'url': 'ht...",en,2013-08-13T20:09:48.000Z,True,367377468870500416.0,This Tweet from @PerezHilton has been withheld...,1.932939e+07,"{'copyright': True, 'country_codes': ['XY'], '...",NaN,1,45.0,27.0,21.0,0.0
4,4,"{'retweet_count': 45, 'reply_count': 0, 'like_...",['367433458140053504'],NaN,en,2013-08-13T23:52:17.000Z,False,367433458140053504.0,This Tweet from @princesitavale has been withh...,2.495303e+07,"{'copyright': True, 'country_codes': ['XY'], '...",NaN,1,45.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
578948,578948,"{'retweet_count': 1815, 'reply_count': 0, 'lik...",['1214389730424631297'],"{'mentions': [{'start': 3, 'end': 18, 'usernam...",en,2020-01-07T03:34:08.000Z,False,1214389730424631297,RT @JonathanTurley: Bolton has reaffirmed that...,8.747957e+08,NaN,NaN,0,1815.0,0.0,0.0,0.0
578949,578949,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",['251862733039992832'],"{'urls': [{'start': 81, 'end': 101, 'url': 'ht...",en,2012-09-29T01:55:29.000Z,False,251862733039992832,"Record rainfall in Midland, TX today with more...",1.566550e+07,NaN,NaN,0,0.0,0.0,0.0,0.0
578950,578950,"{'retweet_count': 1, 'reply_count': 0, 'like_c...",['267581939714764800'],"{'urls': [{'start': 24, 'end': 44, 'url': 'htt...",es,2012-11-11T10:58:00.000Z,False,267581939714764800,Ciencia y Razón is out! http://t.co/xxbvpOUC ▸...,1.593835e+07,NaN,NaN,0,1.0,0.0,1.0,0.0
578951,578951,"{'retweet_count': 30, 'reply_count': 0, 'like_...",['287574899848011777'],"{'mentions': [{'start': 3, 'end': 10, 'usernam...",en,2013-01-05T15:02:53.000Z,False,287574899848011777,RT @nypost: Middle-aged Brooklyn man so upset ...,3.410274e+08,NaN,NaN,0,30.0,0.0,0.0,0.0
578952,578952,"{'retweet_count': 1316, 'reply_count': 0, 'lik...",['280441202430582784'],"{'mentions': [{'start': 3, 'end': 18, 'usernam...",es,2012-12-16T22:36:07.000Z,False,280441202430582784,RT @2010MisterChip: #OJOALDATO - El Barça le s...,5.620389e+07,NaN,NaN,0,1316.0,0.0,0.0,0.0

In [11]:
df.drop(columns=['public_metrics'], inplace=True)
df.to_csv('/cluster/project/sachan/jiarliu/censorship/data/dataset_full.csv')

In [4]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'edit_history_tweet_ids', 'entities',
       'lang', 'created_at', 'possibly_sensitive', 'id', 'text', 'author_id',
       'withheld', 'geo', 'censored', 'retweet_count', 'reply_count',
       'like_count', 'quote_count'],
      dtype='object')